version: '3'

services:
  db:
    image: postgres:alpine

  web:
    build: .
    links:
      - db
    command: ./boot.sh
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
